# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'spade' do
 use_frameworks!

  # Pods for spade

pod 'Kingfisher'
pod 'OAuthSwift'
pod 'YYModel'
pod 'ZFPlayer'
pod 'SVProgressHUD'
pod 'SKPhotoBrowser'
pod 'Popover'
pod 'Bugly'
pod 'Alamofire'
pod 'KeychainAccess'
pod 'FMDB'
end
